%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace.

% Auto-generated by MATLAB (R2025b) and Database Toolbox Version 25.2 on 06-Apr-2026 19:13:48
function [resultado] =  Conexiondb ()
%% Make connection to database
conn = database('mysql2026Diario');

%Set query to execute on the database
query = ['SELECT ID_PRODUCTO_43, ESTADO_43, CANTIDAD_43, ' ...
         'PRECIO_COSTO_43, PRECIO_UNITARIO_43 ' ...
         'FROM parcial_43.producto_43'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query
if isstruct (data)
    resultado = struct2table(data)
elseif iscell(data)
    resultado = cell2table(data)
else 
    resultado = data;
end